apiVersion: v1
kind: Service
metadata:
  name: jksoam-service
spec:
  selector:
    app: jksoam-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Adjust as needed
  type: LoadBalancer # Change to NodePort or ClusterIP if needed